### ISSUE TITLE
Show the real faction only for certain players

### ISSUE THREAD

**Issue by jukkahell** [avesanen/mafiachat#2]
By default return 'unknown' faction for each player in gameInfo's player list. These override the default:
1. Show the real faction for player itself
2. If player is mafioso then he should see other mafiosi
3. Same for cops and doctors

**Comment by avesanen** [comment]
and: 4. Cops see the identify of players they've indentified.

Need to change gameinfo marshaling a bit, just like the messageBuffer was changed as all players see different game status.

**Comment by avesanen** [comment]
Done with new gameInfo struct.
