### ISSUE TITLE
Disable villager chat during night

### ISSUE THREAD

**Issue by jukkahell** [avesanen/mafiachat#24]

**Comment by avesanen** [comment]
Is this needed? Leaving villager chat enabled is more engaging to villagers, as there are only few of them. And writing during night would mean you're not a villager; making it easier for mafia to pick out cops and doctors.

**Comment by jukkahell** [comment]
So, let's keep the public chat enabled always, but instead show the result for cops in the end of the night. That way we can prevent cops to reveal their findings during night.
